### ISSUE TITLE
Uncaught SyntaxError: Unexpected token _

### ISSUE THREAD

**Issue by yriveiro** [Azakur4/autocomplete-php#10]
**Atom Version**: 0.198.0
**System**: Mac OS X 10.10.3
**Thrown From**: [autocomplete-php](https://github.com/Azakur4/autocomplete-php) package, v0.3.3

### Stack Trace

Uncaught SyntaxError: Unexpected token _

```
At file:///opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app.asar/static/index.html#%7B%22locationsToOpen%22%3A%5B%7B%22pathToOpen%22%3A%22%2FUsers%2Fyriveiro%2FDevelopment%2Fbyside%2Fwebcare%2Fweb%22%7D%5D%2C%22bootstrapScript%22%3A%22%2Fopt%2Fhomebrew-cask%2FCaskroom%2Fatom%2Flatest%2FAtom.app%2FContents%2FResources%2Fapp.asar%2Fsrc%2Fwindow-bootstrap.js%22%2C%22resourcePath%22%3A%22%2Fopt%2Fhomebrew-cask%2FCaskroom%2Fatom%2Flatest%2FAtom.app%2FContents%2FResources%2Fapp.asar%22%2C%22devMode%22%3Afalse%2C%22safeMode%22%3Afalse%2C%22apiPreviewMode%22%3Afalse%2C%22profileStartup%22%3Afalse%2C%22appVersion%22%3A%220.198.0%22%2C%22shellLoadTime%22%3A364%2C%22initialPaths%22%3A%5B%22%2FUsers%2Fyriveiro%2FDevelopment%2Fbyside%2Fwebcare%2Fweb%22%5D%7D:1

SyntaxError: Unexpected token _
  at Object.parse (native)
  at Socket.<anonymous> (/Users/yriveiro/.atom/packages/autocomplete-php/lib/provider.coffee:39:31)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:166:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at Socket.Readable.push (_stream_readable.js:109:10)
  at Pipe.onread (net.js:517:20)

```

### Commands

```
  3x -2:36.6.0 core:move-left (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -2:34.3.0 core:save (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -2:19.4.0 core:copy (atom-text-editor.editor.vim-mode.insert-mode.is-focused)
     -2:15.2.0 core:paste (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
  3x -2:14.8.0 core:save (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -2:01.3.0 core:paste (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
     -2:00.9.0 core:save (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -1:53.9.0 core:paste (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
     -1:53.5.0 core:save (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -1:42.1.0 core:paste (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
     -1:41.8.0 core:save (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:11.8.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.vim-mode.command-mode.is-focused)
     -0:08.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:05.7.0 vim-mode:delete (atom-text-editor.editor.vim-mode.is-focused.visual-mode)
     -0:04.9.0 vim-mode:activate-insert-mode (atom-text-editor.editor.vim-mode.is-focused.command-mode)
     -0:03.2.0 core:save (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "autocomplete"
    ],
    "themes": [
      "atom-dark-ui",
      "seti-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.27.1
autocomplete-paths, v1.0.2
autocomplete-php, v0.3.3
autocomplete-plus, v2.14.1
autocomplete-snippets, v1.6.1
color-picker, v1.7.0
docblockr, v0.6.3
file-icons, v1.5.5
git-tab-status, v1.7.0
linter, v0.12.2
linter-php, v0.0.12
linter-shellcheck, v0.0.7
local-history, v3.1.0
markdown-format, v2.5.1
minimap, v4.8.0
minimap-git-diff, v4.1.2
seti-syntax, v0.4.0
travis-ci-status, v0.14.0
vim-mode, v0.46.0
wakatime, v4.0.9

# Dev
No dev packages
```

**Comment by Azakur4** [comment]
can u post a portion of code that throw this error pls.

**Comment by Azakur4** [comment]
New version release pls test to see this issue is fixed

**Comment by yriveiro** [comment]
I think that is fixed no more issues thrown

**Comment by Azakur4** [comment]
ok i will close this then. thanks for feedback
