### ISSUE TITLE
Uncaught SyntaxError: Unexpected token P

### ISSUE THREAD

**Issue by Rydori95** [Azakur4/autocomplete-php#13]
1. I type something like for example "str"
2. the autocomplete dialog shows
3. the error occurs

**Atom Version**: 0.198.0
**System**: RYDORI-PC
**Thrown From**: [autocomplete-php](https://github.com/Azakur4/autocomplete-php) package, v0.3.3

### Stack Trace

Uncaught SyntaxError: Unexpected token P

```
At file:///C:/Users/Rydori/AppData/Local/atom/app-0.198.0/resources/app.asar/static/index.html#%7B%22locationsToOpen%22%3A%5B%7B%22pathToOpen%22%3Anull%7D%5D%2C%22bootstrapScript%22%3A%22C%3A%5C%5CUsers%5C%5CRydori%5C%5CAppData%5C%5CLocal%5C%5Catom%5C%5Capp-0.198.0%5C%5Cresources%5C%5Capp.asar%5C%5Csrc%5C%5Cwindow-bootstrap.js%22%2C%22resourcePath%22%3A%22C%3A%5C%5CUsers%5C%5CRydori%5C%5CAppData%5C%5CLocal%5C%5Catom%5C%5Capp-0.198.0%5C%5Cresources%5C%5Capp.asar%22%2C%22devMode%22%3Afalse%2C%22safeMode%22%3Afalse%2C%22apiPreviewMode%22%3Afalse%2C%22profileStartup%22%3Afalse%2C%22appVersion%22%3A%220.198.0%22%2C%22shellLoadTime%22%3A840%2C%22initialPaths%22%3A%5B%5D%7D:2

SyntaxError: Unexpected token P
    at Object.parse (native)
    at Socket.<anonymous> (C:\Users\Rydori\.atom\packages\autocomplete-php\lib\provider.coffee:46:40)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:166:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:109:10)
    at Pipe.onread (net.js:517:20)
```

### Commands

```
     -0:17.4.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:14.7.0 encoding-selector:show (atom-text-editor.editor)
     -0:13.6.0 grammar-selector:show (atom-text-editor.editor)
     -0:10 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:08.3.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:08.2.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:08.2.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:08.2.0 editor:indent (atom-text-editor.editor.is-focused)
     -0:06.4.0 core:move-down (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:06.2.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "language-smarty-php",
      "default-language",
      "autocomplete-python",
      "autocomplete",
      "robin-language-php"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-html-preview, v0.1.6
autocomplete-css, v0.7.2
autocomplete-html, v0.7.1
autocomplete-php, v0.3.3
autocomplete-plus, v2.14.1
color-picker, v1.7.0
html-entities, v0.3.1
html-helper, v0.2.3
language-htaccess, v0.1.1
language-js-specs, v0.1.0
language-sql-mysql, v0.3.1
language-svg, v0.8.0
minimap, v4.8.0
select-rectangle, v1.0.2

# Dev
No dev packages
```

**Comment by Azakur4** [comment]
i need to see more portion of the code because u start a new file in php and only write the str doesn't reproduce the error

**Comment by Rydori95** [comment]
I Made a new File and then I wrote :
<?php
    str
?>
and after writing str and the dialog opened the error occurs, I can use the auto completion but every time the error comes 
it also came if I used another php command

**Comment by caouecs** [comment]
+1

**Comment by Azakur4** [comment]
New version release pls test to see this issue is fixed

**Comment by caouecs** [comment]
hello,
it's ok for me. Thank you

**Comment by Azakur4** [comment]
glad to know i will for the other respond to close this issue

**Comment by Rydori95** [comment]
it works thanks
