### ISSUE TITLE
Failed to activate the autocomplete-php package

### ISSUE THREAD

**Issue by Sriom** [Azakur4/autocomplete-php#14]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.199.0
**System**: Mac OS X 10.10.3
**Thrown From**: [autocomplete-php](https://github.com/Azakur4/autocomplete-php) package, v0.3.4

### Stack Trace

Failed to activate the autocomplete-php package

```
At fs is not defined

ReferenceError: fs is not defined
    at Object.module.exports.loadCompletions (/Users/Steve/.atom/packages/autocomplete-php/lib/provider.coffee:13:7)
    at Object.module.exports.activate (/Users/Steve/.atom/packages/autocomplete-php/lib/main.coffee:8:23)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:238:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:219:30
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:163:15)
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:211:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:435:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:419:29
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:311:16)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:414:19)
```

### Commands

```
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
autocomplete-php, v0.3.4
file-icons, v1.5.5
grunt-runner, v0.9.1
minimap, v4.8.0
open-last-project, v0.4.1
project-manager, v1.15.5

# Dev
No dev packages
```

**Comment by Azakur4** [comment]
Thanks for inform this i release a new version fixing this issue please test it and tell me if this was fixed

**Comment by Azakur4** [comment]
I release another patch with a fix for problem with the path module in atom 0.199.0

**Comment by taveiralucas** [comment]
Where is the new version? I am user of Atom and it happened to me too . What are the instructions to download?

**Comment by Azakur4** [comment]
Atom always advice u when updates are available. the last version of php autocomplete is 0.3.6

**Comment by justinzelinsky** [comment]
Thanks for the fix! :)

**Comment by Azakur4** [comment]
ur welcome thanks for feedback. closed
