### ISSUE TITLE
Uncaught TypeError: Cannot read property 'username' of undefined

### ISSUE THREAD

**Issue by CasperHK** [Azakur4/autocomplete-php#36]
## Description

When I save a php file, it appears.
![image](https://cloud.githubusercontent.com/assets/6957401/16543840/cefbdaee-411f-11e6-97d5-f4436abab83a.png)
## Error Report

**Atom Version**: 1.8.0
**System**: Microsoft Windows 10 Home
**Thrown From**: [atom-autocomplete-php](https://github.com/Peekmo/atom-autocomplete-php) package, v0.18.9
### Stack Trace

Uncaught TypeError: Cannot read property 'username' of undefined

```
At C:\Users\User\AppData\Local\atom\app-1.8.0\resources\app.asar\src\pane.js:1002

TypeError: Cannot read property 'username' of undefined
    at Object.module.exports.getMemberContext (file:///C:/Users/User/.atom/packages/atom-autocomplete-php/lib/services/php-file-parser.coffee:686:32)
    at FunctionProvider.module.exports.FunctionProvider.extractAnnotationInfo (file:///C:/Users/User/.atom/packages/atom-autocomplete-php/lib/annotation/property-provider.coffee:17:27)
    at FunctionProvider.module.exports.AbstractProvider.placeAnnotation (file:///C:/Users/User/.atom/packages/atom-autocomplete-php/lib/annotation/abstract-provider.coffee:103:27)
    at FunctionProvider.<anonymous> (file:///C:/Users/User/.atom/packages/atom-autocomplete-php/lib/annotation/abstract-provider.coffee:92:18)
    at FunctionProvider.module.exports.AbstractProvider.registerAnnotations (file:///C:/Users/User/.atom/packages/atom-autocomplete-php/lib/annotation/abstract-provider.coffee:91:13)
    at FunctionProvider.module.exports.AbstractProvider.rescan (file:///C:/Users/User/.atom/packages/atom-autocomplete-php/lib/annotation/abstract-provider.coffee:236:10)
    at file:///C:/Users/User/.atom/packages/atom-autocomplete-php/lib/annotation/abstract-provider.coffee:24:18
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\User\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\User\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (C:\Users\User\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1113:27)
    at TextBuffer.module.exports.TextBuffer.save (C:\Users\User\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1083:19)
    at TextEditor.module.exports.TextEditor.save (C:\Users\User\AppData\Local\atom\app-1.8.0\resources\app.asar\src\text-editor.js:660:26)
    at Pane.module.exports.Pane.saveItem (C:\Users\User\AppData\Local\atom\app-1.8.0\resources\app.asar\src\pane.js:718:18)
    at Pane.module.exports.Pane.saveActiveItem (C:\Users\User\AppData\Local\atom\app-1.8.0\resources\app.asar\src\pane.js:701:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (C:\Users\User\AppData\Local\atom\app-1.8.0\resources\app.asar\src\workspace.js:684:35)
    at atom-workspace.commandRegistry.add.core:save (C:\Users\User\AppData\Local\atom\app-1.8.0\resources\app.asar\src\register-default-commands.js:214:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\User\AppData\Local\atom\app-1.8.0\resources\app.asar\src\command-registry.js:260:29)
    at C:\Users\User\AppData\Local\atom\app-1.8.0\resources\app.asar\src\command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\User\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\User\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (C:\Users\User\AppData\Local\atom\app-1.8.0\resources\app.asar\src\window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (C:\Users\User\AppData\Local\atom\app-1.8.0\resources\app.asar\src\window-event-handler.js:3:61)
```
### Commands

```
  2x -3:34.6.0 core:copy (atom-pane.pane.active)
     -3:13.1.0 core:save (atom-text-editor.editor.is-focused.power-mode)
     -3:10.5.0 core:backspace (atom-text-editor.editor.is-focused.power-mode)
     -3:09.2.0 core:save (atom-text-editor.editor.is-focused.power-mode)
     -1:42.7.0 core:backspace (atom-text-editor.editor.power-mode.is-focused)
     -1:41.3.0 core:save (atom-text-editor.editor.power-mode.is-focused)
     -1:10 find-and-replace:show (atom-text-editor.editor.power-mode.is-focused)
     -1:05.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -0:38.6.0 core:backspace (atom-text-editor.editor.power-mode.is-focused)
     -0:37.3.0 core:move-left (atom-text-editor.editor.power-mode.is-focused)
     -0:36.9.0 editor:newline (atom-text-editor.editor.power-mode.is-focused)
  2x -0:35.8.0 core:save (atom-text-editor.editor.power-mode.is-focused)
     -0:09.8.0 editor:newline (atom-text-editor.editor.power-mode.is-focused)
  2x -0:08.0 core:save (atom-text-editor.editor.power-mode.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "atom-terminal-panel",
      "linter"
    ],
    "themes": [
      "atom-material-ui",
      "atom-material-syntax-dark"
    ]
  },
  "atom-autocomplete-php": {}
}
```
### Installed Packages

``` coffee
# User
activate-power-mode, v0.7.0
atom-autocomplete-php, v0.18.9
atom-beautify, v0.29.9
atom-material-syntax-dark, v0.2.5
atom-material-ui, v1.2.13
autocomplete-go, v1.1.0
autocomplete-modules, v1.5.2
builder-go, v1.0.0
go-config, v1.1.4
go-get, v1.0.3
go-plus, v4.1.0
gofmt, v1.1.6
gometalinter-linter, v1.1.0
gorename, v1.0.2
highlight-selected, v0.11.2
navigator-godef, v1.0.3
pigments, v0.29.3
react, v0.15.0
Remote-FTP, v0.8.3
remote-sync, v4.1.2
sync-settings, v0.7.2
tester-go, v1.0.4

# Dev
No dev packages
```

**Comment by rdelpeso** [comment]
Maybe am missing something, but from your post it seems that this error is not related to this package. Instead it mentions https://github.com/Peekmo/atom-autocomplete-php. So it seems this is the wrong place to report this error.
