### ISSUE TITLE
Cannot find module 'jquery'

### ISSUE THREAD

**Issue by bestrong89** [Azakur4/autocomplete-php#49]
This pops up at seemingly random times...

![screen shot 2018-01-16 at 11 20 49 am](https://user-images.githubusercontent.com/12430891/34999282-5f286e94-faaf-11e7-8053-d46745761675.png)

Here is the error text:

/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1
Hide Stack Trace
Error: Cannot find module 'jquery'
    at Module._resolveFilename (module.js:470:15)
    at Module._resolveFilename (/Applications/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:354:58)
    at Module.require (file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.js:40:43)
    at require (/Applications/Atom.app/Contents/Resources/app/src/native-compile-cache.js:66:33)
    at Object.getClassSelectorFromEvent (/Users/ben/.atom/packages/atom-autocomplete-php/lib/services/php-file-parser.coffee:780:11)
    at ClassProvider.module.exports.ClassProvider.getSelectorFromEvent (/Users/ben/.atom/packages/atom-autocomplete-php/lib/tooltip/class-provider.coffee:71:26)
    at HTMLSpanElement.<anonymous> (/Users/ben/.atom/packages/atom-autocomplete-php/lib/tooltip/abstract-provider.coffee:106:30)
    at HTMLDivElement.dispatch (/Users/ben/.atom/packages/atom-autocomplete-php/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/Users/ben/.atom/packages/atom-autocomplete-php/node_modules/jquery/dist/jquery.js:4121:28)

**Comment by 80boys** [comment]
please install atom-jquery
