### ISSUE TITLE
autocomplete php not working

### ISSUE THREAD

**Issue by soheljaman** [Azakur4/autocomplete-php#54]
autocomplete php not working
![php](https://user-images.githubusercontent.com/26348787/55414482-02f6f700-558d-11e9-9ee4-809958a516b8.PNG)

**Comment by AWS-ServerLink** [comment]
![image](https://user-images.githubusercontent.com/36523020/56729332-eb0a3180-674c-11e9-8583-73967683dae7.png)

Uncaught (in promise) Error: Fetching outdated packages and themes failed.
    at C:\Users\xxxxxxxxx\AppData\Local\atom\app-1.36.0\resources\app\static\<embedded>:11:895602
    at r (C:\Users\xxxxxxxxx\AppData\Local\atom\app-1.36.0\resources\app\static\<embedded>:11:893618)
    at o (C:\Users\xxxxxxxxx\AppData\Local\atom\app-1.36.0\resources\app\static\<embedded>:14:1032937)
    at ChildProcess.n.process.on.e (C:\Users\xxxxxxxxx\AppData\Local\atom\app-1.36.0\resources\app\static\<embedded>:14:1033143)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
util.js:1024 Uncaught (in promise) Error: write EPIPE
    at _errnoException (util.js:1024:11)
    at Socket._writeGeneric (net.js:767:25)
    at Socket._write (net.js:786:8)
    at doWrite (_stream_writable.js:387:12)
    at writeOrBuffer (_stream_writable.js:373:5)
    at Socket.Writable.write (_stream_writable.js:290:11)
    at Socket.write (net.js:704:40)
    at Object.execute (file:///C:/Users/xxxxxxxxx/.atom/packages/autocomplete-php/lib/provider.coffee:40:16)
    at file:///C:/Users/xxxxxxxxx/.atom/packages/autocomplete-php/lib/provider.coffee:78:10
    at new Promise (<anonymous>)
    at Object.getSuggestions (file:///C:/Users/xxxxxxxxx/.atom/packages/autocomplete-php/lib/provider.coffee:61:5)
    at n.forEach.t (C:\Users\xxxxxxxxx\AppData\Local\atom\app-1.36.0\resources\app\static\<embedded>:11:631470)
    at Array.forEach (<anonymous>)
    at AutocompleteManager.getSuggestionsFromProviders (C:\Users\xxxxxxxxx\AppData\Local\atom\app-1.36.0\resources\app\static\<embedded>:11:630986)
    at AutocompleteManager.findSuggestions (C:\Users\xxxxxxxxx\AppData\Local\atom\app-1.36.0\resources\app\static\<embedded>:11:630724)
    at AutocompleteManager.requestNewSuggestions (C:\Users\xxxxxxxxx\AppData\Local\atom\app-1.36.0\resources\app\static\<embedded>:11:639257)
    at AutocompleteManager.showOrHideSuggestionListForBufferChanges (C:\Users\xxxxxxxxx\AppData\Local\atom\app-1.36.0\resources\app\static\<embedded>:11:640348)
    at Function.simpleDispatch (C:\Users\xxxxxxxxx\AppData\Local\atom\app-1.36.0\resources\app\static\<embedded>:11:1172021)
    at Emitter.emit (C:\Users\xxxxxxxxx\AppData\Local\atom\app-1.36.0\resources\app\static\<embedded>:11:1173462)
    at TextBuffer.emitDidChangeTextEvent (C:\Users\xxxxxxxxx\AppData\Local\atom\app-1.36.0\resources\app\static\<embedded>:11:504326)
    at TextBuffer.transact (C:\Users\xxxxxxxxx\AppData\Local\atom\app-1.36.0\resources\app\static\<embedded>:11:492501)
    at TextEditor.transact (C:\Users\xxxxxxxxx\AppData\Local\atom\app-1.36.0\resources\app\static\<embedded>:11:24215)
    at mergeIntersectingSelections (C:\Users\xxxxxxxxx\AppData\Local\atom\app-1.36.0\resources\app\static\<embedded>:11:16150)
    at TextEditor.mergeSelections (C:\Users\xxxxxxxxx\AppData\Local\atom\app-1.36.0\resources\app\static\<embedded>:11:39529)
    at TextEditor.mergeIntersectingSelections (C:\Users\xxxxxxxxx\AppData\Local\atom\app-1.36.0\resources\app\static\<embedded>:11:39038)
    at TextEditor.mutateSelectedText (C:\Users\xxxxxxxxx\AppData\Local\atom\app-1.36.0\resources\app\static\<embedded>:11:16113)
    at TextEditor.insertText (C:\Users\xxxxxxxxx\AppData\Local\atom\app-1.36.0\resources\app\static\<embedded>:11:15662)
    at TextEditor.e.(anonymous function) [as insertText] (C:\Users\xxxxxxxxx\AppData\Local\atom\app-1.36.0\resources\app\static\<embedded>:11:259469)
    at TextEditorComponent.didTextInput (C:\Users\xxxxxxxxx\AppData\Local\atom\app-1.36.0\resources\app\static\<embedded>:11:93937)
events.js:183 Uncaught Error: spawn php ENOENT
    at _errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by AWS-ServerLink** [comment]
> autocomplete php not working
> ![php](https://user-images.githubusercontent.com/26348787/55414482-02f6f700-558d-11e9-9ee4-809958a516b8.PNG)

autocomplete-php cannot find your php runtime.
