### ISSUE TITLE
Uncaught SyntaxError: Unexpected token ,

### ISSUE THREAD

**Issue by hungnv24** [Azakur4/autocomplete-php#9]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.198.0
**System**: Mac OS X 10.10.3
**Thrown From**: [autocomplete-php](https://github.com/Azakur4/autocomplete-php) package, v0.3.3

### Stack Trace

Uncaught SyntaxError: Unexpected token ,

```
At file:///Applications/Atom.app/Contents/Resources/app.asar/static/index.html#%7B%22locationsToOpen%22%3A%5B%7B%22pathToOpen%22%3A%22%2FUsers%2Fhung.v.nguyen%2FDesktop%2FRageServer%22%7D%5D%2C%22bootstrapScript%22%3A%22%2FApplications%2FAtom.app%2FContents%2FResources%2Fapp.asar%2Fsrc%2Fwindow-bootstrap.js%22%2C%22resourcePath%22%3A%22%2FApplications%2FAtom.app%2FContents%2FResources%2Fapp.asar%22%2C%22devMode%22%3Afalse%2C%22safeMode%22%3Afalse%2C%22apiPreviewMode%22%3Afalse%2C%22appVersion%22%3A%220.198.0%22%2C%22shellLoadTime%22%3A507%2C%22initialPaths%22%3A%5B%22%2FUsers%2Fhung.v.nguyen%2FDesktop%2FRageServer%22%5D%7D:1

SyntaxError: Unexpected token ,
  at Object.parse (native)
  at Socket.<anonymous> (/Users/hung.v.nguyen/.atom/packages/autocomplete-php/lib/provider.coffee:39:31)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:166:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at Socket.Readable.push (_stream_readable.js:109:10)
  at Pipe.onread (net.js:517:20)

```

### Commands

```
  7x -5:43.5.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
 34x -5:37.1.0 core:undo (atom-text-editor.editor.is-focused.autocomplete-active)
     -5:32 core:save (atom-text-editor.editor.is-focused)
     -5:29.6.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -5:27.3.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -5:27.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -5:24.6.0 editor:newline (atom-text-editor.editor.is-focused)
 16x -5:03.0 core:backspace (atom-text-editor.editor.autocomplete-active.is-focused)
     -4:52.4.0 core:save (atom-text-editor.editor.is-focused)
     -1:29.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:10.3.0 core:move-up (atom-text-editor.editor.is-focused)
     -1:10 editor:newline (atom-text-editor.editor.is-focused)
 15x -1:08.4.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -0:59.8.0 core:save (atom-text-editor.editor.is-focused)
     -0:04.2.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:00.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
```

### Config

```json
{
  "core": {
    "ignoredNames": [
      "flash_sp",
      "flash",
      "image_sp",
      "application/cache"
    ],
    "disabledPackages": []
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-php, v0.3.3
autocomplete-plus, v2.14.1
color-picker, v1.7.0

# Dev
No dev packages
```

**Comment by Azakur4** [comment]
can u post a portion of code that throw this error pls.

**Comment by Azakur4** [comment]
New version release pls test to see this issue is fixed

**Comment by Azakur4** [comment]
I will close this for inactivity, if the problem persist please let me know to re-open this issue.
